name: sidecar-search-dev
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pytorch-gpu~=2.6
  - sentence-transformers~=3.4
  - tqdm
  - numpy>=1.26.4
  - pyarrow
  - pytorch::faiss-gpu~=1.9
  - datasets>=3.3.2
  # development only
  - pyarrow-stubs
  - pyright
  - pytest
  - coverage
